### ISSUE TITLE
cannot import name fit_plane_to_surface1

### ISSUE THREAD

**Issue by hvontres** [hamish2014/FreeCAD_assembly2#38]
Trying to use the latest version on last night's freecad build I get the folowing error:

Traceback (most recent call last):
  File "/home/henry/.FreeCAD/Mod/FreeCAD_assembly2/importPart.py", line 5, in <module>
    from assembly2lib import *
  File "/home/henry/.FreeCAD/Mod/FreeCAD_assembly2/assembly2lib.py", line 16, in <module>
    from lib3D import fit_plane_to_surface1, fit_rotation_axis_to_surface1
<type 'exceptions.ImportError'>: cannot import name fit_plane_to_surface1
Traceback (most recent call last):
  File "/home/henry/.FreeCAD/Mod/FreeCAD_assembly2/importPart.py", line 5, in <module>
    from assembly2lib import *
  File "/home/henry/.FreeCAD/Mod/FreeCAD_assembly2/assembly2lib.py", line 16, in <module>
    from lib3D import fit_plane_to_surface1, fit_rotation_axis_to_surface1
<type 'exceptions.ImportError'>: cannot import name fit_plane_to_surface1
Traceback (most recent call last):
  File "/home/henry/.FreeCAD/Mod/FreeCAD_assembly2/assembly2lib.py", line 16, in <module>
    from lib3D import fit_plane_to_surface1, fit_rotation_axis_to_surface1
<type 'exceptions.ImportError'>: cannot import name fit_plane_to_surface1
Traceback (most recent call last):
  File "/home/henry/.FreeCAD/Mod/FreeCAD_assembly2/assembly2lib.py", line 16, in <module>
    from lib3D import fit_plane_to_surface1, fit_rotation_axis_to_surface1
<type 'exceptions.ImportError'>: cannot import name fit_plane_to_surface1
Traceback (most recent call last):
  File "/home/henry/.FreeCAD/Mod/FreeCAD_assembly2/assembly2lib.py", line 16, in <module>
    from lib3D import fit_plane_to_surface1, fit_rotation_axis_to_surface1
<type 'exceptions.ImportError'>: cannot import name fit_plane_to_surface1
cannot import name fit_plane_to_surface1

**Comment by hamish2014** [comment]
Hi,

I believe this is a repeat of #33 
try deleting all the *.pyc files in the assembly2 directory.

**Comment by hvontres** [comment]
Thanks. I had tried deleting the ones in assembly2, but I didn't see the one in drawing_dimensioning, which happend to be first in sys.path.
